.TH CANORUS 6 "Nov 19, 2006"
.SH NAME
canorus \- a free cross-platform music score editor
.SH SYNOPSIS
.B canorus
.RI [ options ] " filename"
.br
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBcanorus\fP is a free cross-platform music score editor written in Qt4.
It supports various features like plugins engine via Python and Ruby
scripting languages, score source view, various import and export filters
like LilyPond, MusicXML and NoteEdit.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Display the version of Canorus you're running.
.SH AUTHOR
This manual page was written by Matev¿ Jekovec <matevz.jekovec@gmail.com>,
for the Debian project (but may be used by others).
