.TH CANORUS 6 "Mar 07, 2009"
.SH NAME
canorus \- a free cross-platform music score editor
.SH SYNOPSIS
.B canorus
.RI [ options ] " filename"
.br
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBcanorus\fP is a free cross-platform music score editor written.
It supports a standard western music notation and uses a modern Qt4 GUI.
Canorus is extensible by using plugins written in Python or native C++.
Canorus uses its own .xml format for the document, but supports import
and export filters like LilyPond, MusicXML, NoteEdit, PDF and Midi.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Display the version of Canorus you're running.
.SH AUTHOR
This manual page was written by Matevz Jekovec <matevz.jekovec@gmail.com>,
for the Debian project (but may be used by others).
