on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        no_python: [0, 1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          modules: qtwebengine

      - name: Install other deps
        run: |
          sudo apt install -y cmake libasound2-dev

      - name: CMake (NO_PYTHON=${{ matrix.no_python }})
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=~/.local -DNO_PYTHON=${{ matrix.no_python }}

      - name: Make
        working-directory: build
        run: |
          make -j4

      - name: Build translations
        working-directory: build
        run: |
          make tr

      - name: Install
        working-directory: build
        run: |
          make install
